from django.urls import path
from prontuario.views import *

urlpatterns = [
    path("anamnese-detalhes/<int:pk>/", anamnese_detalhes, name="anamnese_detalhes"),
    path("anamnese-edit/<int:pk>/", AnamneseUpdate.as_view(), name="anamnese_edit"),
    path("inf-sau-sis-detalhes/<int:pk>/", inf_saude_sistemica_detalhes, name="inf_sau_sis_detalhes"),
    path("inf-sau-sis-edit/<int:pk>/", InfSaudeSistemicaUpdate.as_view(), name="inf_sau_sis_edit"),
    path("exa-fis-detalhes/<int:pk>/", exame_fisico_detalhes, name="exa_fis_detalhes"),
    path("exa-fis-edit/<int:pk>/", ExameFisicoUpdate.as_view(), name="exa_fis_edit"),
    path("sin-vit-cli-detalhes/<int:pk>/", sinais_vitais_clinicos_detalhes, name="sin_vit_cli_detalhes"),
    path("sin-vit-cli-edit/<int:pk>/", SinaisVitaisClinicosUpdate.as_view(), name="sin_vit_cli_edit"),
    path("psr-detalhes/<int:pk>/", psr_detalhes, name="psr_detalhes"),
    path("psr-edit/<int:pk>/", PSRUpdate.as_view(), name="psr_edit"),
    path("odo-detalhes/<int:pk>", odon_detalhes, name="odon_detalhes"),
    path("odo-edit/<int:pk>/", OdontogramaUpdate.as_view(), name="odo_edit"),
    path("sol-exa-com-detalhes/<int:pk>/", sol_exa_com_detalhes, name="sol_exa_com_detalhes"),
    path("sol-exa-com-edit/<int:pk>/", SolicitacaoExamesComplementaresUpdate.as_view(), name="sol_exa_com_edit"),

    path("sup-18/<int:pk>", sup18, name="sup18"),
    path("sup-18-edit/<int:pk>", sup18_edit, name="sup18_edit"),
    path("sup-17/<int:pk>/", sup17, name="sup17"),
    path("sup-17-edit/<int:pk>", sup17_edit, name="sup17_edit"),
    path("sup-16/<int:pk>/", sup16, name="sup16"),
    path("sup-16-edit/<int:pk>", sup16_edit, name="sup16_edit"),
    path("sup-15/<int:pk>/", sup15, name="sup15"),
    path("sup-15-edit/<int:pk>", sup15_edit, name="sup15_edit"),
    path("sup-14/<int:pk>/", sup14, name="sup14"),
    path("sup-14-edit/<int:pk>", sup14_edit, name="sup14_edit"),
    path("sup-13/<int:pk>/", sup13, name="sup13"),
    path("sup-13-edit/<int:pk>", sup13_edit, name="sup13_edit"),
    path("sup-12/<int:pk>/", sup12, name="sup12"),
    path("sup-12-edit/<int:pk>", sup12_edit, name="sup12_edit"),
    path("sup-11/<int:pk>/", sup11, name="sup11"),
    path("sup-11-edit/<int:pk>", sup11_edit, name="sup11_edit"),

    path("sup-21/<int:pk>/", sup21, name="sup21"),
    path("sup-21-edit/<int:pk>", sup21_edit, name="sup21_edit"),
    path("sup-22/<int:pk>/", sup22, name="sup22"),
    path("sup-22-edit/<int:pk>", sup22_edit, name="sup22_edit"),
    path("sup-23/<int:pk>/", sup23, name="sup23"),
    path("sup-23-edit/<int:pk>", sup23_edit, name="sup23_edit"),
    path("sup-24/<int:pk>/", sup24, name="sup24"),
    path("sup-24-edit/<int:pk>", sup24_edit, name="sup24_edit"),
    path("sup-25/<int:pk>/", sup25, name="sup25"),
    path("sup-25-edit/<int:pk>", sup25_edit, name="sup25_edit"),
    path("sup-26/<int:pk>/", sup26, name="sup26"),
    path("sup-26-edit/<int:pk>", sup26_edit, name="sup26_edit"),
    path("sup-27/<int:pk>/", sup27, name="sup27"),
    path("sup-27-edit/<int:pk>", sup27_edit, name="sup27_edit"),
    path("sup-28/<int:pk>/", sup28, name="sup28"),
    path("sup-28-edit/<int:pk>", sup28_edit, name="sup28_edit"),

    path("sup-48/<int:pk>/", sup48, name="sup48"),
    path("sup-48-edit/<int:pk>", sup48_edit, name="sup48_edit"),
    path("sup-47/<int:pk>/", sup47, name="sup47"),
    path("sup-47-edit/<int:pk>", sup47_edit, name="sup47_edit"),
    path("sup-46/<int:pk>/", sup46, name="sup46"),
    path("sup-46-edit/<int:pk>", sup46_edit, name="sup46_edit"),
    path("sup-45/<int:pk>/", sup45, name="sup45"),
    path("sup-45-edit/<int:pk>", sup45_edit, name="sup45_edit"),
    path("sup-44/<int:pk>/", sup44, name="sup44"),
    path("sup-44-edit/<int:pk>", sup44_edit, name="sup44_edit"),
    path("sup-43/<int:pk>/", sup43, name="sup43"),
    path("sup-43-edit/<int:pk>", sup43_edit, name="sup43_edit"),
    path("sup-42/<int:pk>/", sup42, name="sup42"),
    path("sup-42-edit/<int:pk>", sup42_edit, name="sup42_edit"),
    path("sup-41/<int:pk>/", sup41, name="sup41"),
    path("sup-41-edit/<int:pk>", sup41_edit, name="sup41_edit"),

    path("sup-31/<int:pk>/", sup31, name="sup31"),
    path("sup-31-edit/<int:pk>", sup31_edit, name="sup31_edit"),
    path("sup-32/<int:pk>/", sup32, name="sup32"),
    path("sup-32-edit/<int:pk>", sup32_edit, name="sup32_edit"),
    path("sup-33/<int:pk>/", sup33, name="sup33"),
    path("sup-33-edit/<int:pk>", sup33_edit, name="sup33_edit"),
    path("sup-34/<int:pk>/", sup34, name="sup34"),
    path("sup-34-edit/<int:pk>", sup34_edit, name="sup34_edit"),
    path("sup-35/<int:pk>/", sup35, name="sup35"),
    path("sup-35-edit/<int:pk>", sup35_edit, name="sup35_edit"),
    path("sup-36/<int:pk>/", sup36, name="sup36"),
    path("sup-36-edit/<int:pk>", sup36_edit, name="sup36_edit"),
    path("sup-37/<int:pk>/", sup37, name="sup37"),
    path("sup-37-edit/<int:pk>", sup37_edit, name="sup37_edit"),
    path("sup-38/<int:pk>/", sup38, name="sup38"),
    path("sup-38-edit/<int:pk>", sup38_edit, name="sup38_edit"),

    path("create-data/", create_data, name="create_data"),
]
