# Generated by Django 4.0.3 on 2023-04-20 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_teste_teste2_paciente_prontuario_and_more'),
        ('prontuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prontuario', models.CharField(blank=True, max_length=200, verbose_name='prontuario')),
                ('nome', models.CharField(blank=True, max_length=3, verbose_name='Dente')),
            ],
            options={
                'verbose_name_plural': 'Dentes',
            },
        ),
        migrations.CreateModel(
            name='Estenografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(blank=True, choices=[('carie', 'Carie'), ('cáries', 'cáries'), ('gengivite', 'gengivite'), ('tártaro', 'tártaro'), ('infecções', 'infecções'), ('sensibilidade', 'sensibilidade'), ('nenhuma', 'nenhuma')], default='nenhuma', max_length=25, verbose_name='nome')),
            ],
            options={
                'verbose_name_plural': 'Estenografia',
            },
        ),
        migrations.CreateModel(
            name='Odontograma',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('prontuario', models.CharField(blank=True, max_length=200, verbose_name='prontuario')),
                ('dente_11', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odontograma_dente_11', to='prontuario.dente')),
                ('dente_12', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odontograma_dente_12', to='prontuario.dente')),
                ('dente_13', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odontograma_dente_13', to='prontuario.dente')),
                ('dente_14', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odontograma_dente_14', to='prontuario.dente')),
                ('dente_15', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odontograma_dente_15', to='prontuario.dente')),
                ('dente_16', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odontograma_dente_16', to='prontuario.dente')),
                ('dente_17', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odontograma_dente_17', to='prontuario.dente')),
                ('dente_18', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odontograma_dente_18', to='prontuario.dente')),
                ('dente_21', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odontograma_dente_21', to='prontuario.dente')),
                ('dente_22', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odontograma_dente_22', to='prontuario.dente')),
                ('dente_23', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odontograma_dente_23', to='prontuario.dente')),
                ('dente_24', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odontograma_dente_24', to='prontuario.dente')),
                ('dente_25', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odontograma_dente_25', to='prontuario.dente')),
                ('dente_26', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odontograma_dente_26', to='prontuario.dente')),
                ('dente_27', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odontograma_dente_27', to='prontuario.dente')),
                ('dente_28', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odontograma_dente_28', to='prontuario.dente')),
                ('dente_31', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odontograma_dente_31', to='prontuario.dente')),
                ('dente_32', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odontograma_dente_32', to='prontuario.dente')),
                ('dente_33', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odontograma_dente_33', to='prontuario.dente')),
                ('dente_34', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odontograma_dente_34', to='prontuario.dente')),
                ('dente_35', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odontograma_dente_35', to='prontuario.dente')),
                ('dente_36', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odontograma_dente_36', to='prontuario.dente')),
                ('dente_37', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odontograma_dente_37', to='prontuario.dente')),
                ('dente_38', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odontograma_dente_38', to='prontuario.dente')),
                ('dente_41', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odontograma_dente_41', to='prontuario.dente')),
                ('dente_42', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odontograma_dente_42', to='prontuario.dente')),
                ('dente_43', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odontograma_dente_43', to='prontuario.dente')),
                ('dente_44', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odontograma_dente_44', to='prontuario.dente')),
                ('dente_45', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odontograma_dente_45', to='prontuario.dente')),
                ('dente_46', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odontograma_dente_46', to='prontuario.dente')),
                ('dente_47', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odontograma_dente_47', to='prontuario.dente')),
                ('dente_48', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odontograma_dente_48', to='prontuario.dente')),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
            ],
            options={
                'verbose_name_plural': 'Odontogramas',
            },
        ),
        migrations.RemoveField(
            model_name='odontogramainicial',
            name='prontuario',
        ),
        migrations.RemoveField(
            model_name='planotratamentoi',
            name='prontuario',
        ),
        migrations.RemoveField(
            model_name='planotratamentoii',
            name='prontuario',
        ),
        migrations.RemoveField(
            model_name='prontuario',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='resultadoexamescomplementares',
            name='prontuario',
        ),
        migrations.AlterModelOptions(
            name='anamnese',
            options={'verbose_name_plural': 'Anamneses'},
        ),
        migrations.AlterModelOptions(
            name='examefisico',
            options={'verbose_name_plural': 'Exames Fisicos'},
        ),
        migrations.AlterModelOptions(
            name='infsaudesistemica',
            options={'verbose_name_plural': 'Informações de Saúde Sistêmicas'},
        ),
        migrations.AlterModelOptions(
            name='psr',
            options={'verbose_name_plural': "PSR's"},
        ),
        migrations.AlterModelOptions(
            name='sinaisvitaisclinicos',
            options={'verbose_name_plural': 'Sinais Vitais Clinicos'},
        ),
        migrations.AlterModelOptions(
            name='solicitacaoexamescomplementares',
            options={'verbose_name_plural': 'Solicitações Exames Complementares'},
        ),
        migrations.AddField(
            model_name='anamnese',
            name='paciente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente'),
        ),
        migrations.AddField(
            model_name='examefisico',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente'),
        ),
        migrations.AddField(
            model_name='infsaudesistemica',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente'),
        ),
        migrations.AddField(
            model_name='psr',
            name='paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente'),
        ),
        migrations.AddField(
            model_name='sinaisvitaisclinicos',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente'),
        ),
        migrations.AddField(
            model_name='solicitacaoexamescomplementares',
            name='paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente'),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='prontuario',
            field=models.CharField(blank=True, max_length=200, verbose_name='prontuario'),
        ),
        migrations.AlterField(
            model_name='examefisico',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='examefisico',
            name='prontuario',
            field=models.CharField(blank=True, max_length=200, verbose_name='prontuario'),
        ),
        migrations.AlterField(
            model_name='infsaudesistemica',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='infsaudesistemica',
            name='prontuario',
            field=models.CharField(blank=True, max_length=200, verbose_name='prontuario'),
        ),
        migrations.AlterField(
            model_name='psr',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='psr',
            name='prontuario',
            field=models.CharField(blank=True, max_length=200, verbose_name='prontuario'),
        ),
        migrations.AlterField(
            model_name='sinaisvitaisclinicos',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sinaisvitaisclinicos',
            name='indice',
            field=models.CharField(blank=True, max_length=5, verbose_name='Indíce'),
        ),
        migrations.AlterField(
            model_name='sinaisvitaisclinicos',
            name='pressao_arterial',
            field=models.TextField(blank=True, verbose_name='Pressão Arterial'),
        ),
        migrations.AlterField(
            model_name='sinaisvitaisclinicos',
            name='prontuario',
            field=models.CharField(blank=True, max_length=200, verbose_name='prontuario'),
        ),
        migrations.AlterField(
            model_name='sinaisvitaisclinicos',
            name='pulso',
            field=models.TextField(blank=True, verbose_name='Pulso'),
        ),
        migrations.AlterField(
            model_name='sinaisvitaisclinicos',
            name='respiracao',
            field=models.TextField(blank=True, verbose_name='Respiração'),
        ),
        migrations.AlterField(
            model_name='sinaisvitaisclinicos',
            name='resultado',
            field=models.CharField(blank=True, choices=[('Higiene Boa', 'Higiene Boa'), ('Higiene Regular', 'Higiene regular'), ('Higiene Ruim', 'Higiene Ruim')], max_length=15, verbose_name='Resultado'),
        ),
        migrations.AlterField(
            model_name='sinaisvitaisclinicos',
            name='temperatura',
            field=models.TextField(blank=True, verbose_name='Temperatura'),
        ),
        migrations.AlterField(
            model_name='solicitacaoexamescomplementares',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='solicitacaoexamescomplementares',
            name='prontuario',
            field=models.CharField(blank=True, max_length=200, verbose_name='prontuario'),
        ),
        migrations.AlterField(
            model_name='solicitacaoexamescomplementares',
            name='sol_exa_com',
            field=models.TextField(blank=True, verbose_name='Solicitação Exames Complementares'),
        ),
        migrations.DeleteModel(
            name='EvolucaoPaciente',
        ),
        migrations.DeleteModel(
            name='OdontogramaInicial',
        ),
        migrations.DeleteModel(
            name='PlanoTratamentoI',
        ),
        migrations.DeleteModel(
            name='PlanoTratamentoII',
        ),
        migrations.DeleteModel(
            name='Prontuario',
        ),
        migrations.DeleteModel(
            name='ResultadoExamesComplementares',
        ),
        migrations.AddField(
            model_name='dente',
            name='distal',
            field=models.ManyToManyField(blank=True, related_name='dente_distal', to='prontuario.estenografia'),
        ),
        migrations.AddField(
            model_name='dente',
            name='lingual',
            field=models.ManyToManyField(blank=True, related_name='dente_lingual', to='prontuario.estenografia'),
        ),
        migrations.AddField(
            model_name='dente',
            name='mesial',
            field=models.ManyToManyField(blank=True, related_name='dente_mesial', to='prontuario.estenografia'),
        ),
        migrations.AddField(
            model_name='dente',
            name='oclusal',
            field=models.ManyToManyField(blank=True, related_name='dente_oclusal', to='prontuario.estenografia'),
        ),
        migrations.AddField(
            model_name='dente',
            name='paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente'),
        ),
        migrations.AddField(
            model_name='dente',
            name='vestibular',
            field=models.ManyToManyField(blank=True, related_name='dente_vestibular', to='prontuario.estenografia'),
        ),
    ]
