# Generated by Django 4.0.3 on 2022-11-21 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Atendimentos',
            },
        ),
        migrations.CreateModel(
            name='Dente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, choices=[('D11', 'D11'), ('D12', 'D12'), ('D13', 'D13'), ('D14', 'D14'), ('D15', 'D15'), ('D16', 'D16'), ('D17', 'D17'), ('D18', 'D18'), ('D21', 'D21'), ('D22', 'D23'), ('D23', 'D23'), ('D24', 'D24'), ('D25', 'D25'), ('D26', 'D26'), ('D27', 'D27'), ('D28', 'D28'), ('D31', 'D31'), ('D32', 'D32'), ('D33', 'D33'), ('D34', 'D34'), ('D35', 'D35'), ('D36', 'D36'), ('D37', 'D37'), ('D38', 'D38'), ('D41', 'D41'), ('D42', 'D42'), ('D43', 'D43'), ('D44', 'D44'), ('D45', 'D45'), ('D46', 'D46'), ('D47', 'D47'), ('D48', 'D48')], max_length=3, verbose_name='Dente')),
            ],
            options={
                'verbose_name_plural': 'Dentes',
            },
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dente', models.ForeignKey(blank=True, default='D11', on_delete=django.db.models.deletion.CASCADE, to='prontuario.dente')),
            ],
            options={
                'verbose_name_plural': 'Diagnosticos',
            },
        ),
        migrations.CreateModel(
            name='Doenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.TextField(blank=True, choices=[('carie', 'Carie'), ('canal', 'Canal'), ('cáries', 'cáries'), ('gengivite', 'gengivite'), ('tártaro', 'tártaro'), ('infecções', 'infecções'), ('sensibilidade', 'sensibilidade'), ('nenhuma', 'nenhuma')], default='nenhuma', verbose_name='Doença')),
            ],
            options={
                'verbose_name_plural': 'Doenças',
            },
        ),
        migrations.CreateModel(
            name='Odontograma',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Odontogramas',
            },
        ),
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, choices=[('limpeza', 'limpeza'), ('remoção de tartaro', 'remoção de tartaro'), ('aplicacao de fluor', 'aplicacao de fluor'), ('nenhum', 'nenhum')], default='nenhum', max_length=100, verbose_name='procedimento')),
            ],
        ),
        migrations.RemoveField(
            model_name='planotratamentoi',
            name='prontuario',
        ),
        migrations.RemoveField(
            model_name='planotratamentoii',
            name='prontuario',
        ),
        migrations.AlterModelOptions(
            name='anamnese',
            options={'verbose_name_plural': 'Anamneses'},
        ),
        migrations.AlterModelOptions(
            name='examefisico',
            options={'verbose_name_plural': 'Exames Fisicos'},
        ),
        migrations.AlterModelOptions(
            name='infsaudesistemica',
            options={'verbose_name_plural': 'Informações de Saúde Sistêmicas'},
        ),
        migrations.AlterModelOptions(
            name='odontogramainicial',
            options={'verbose_name_plural': 'Odontogramas Iniciais'},
        ),
        migrations.AlterModelOptions(
            name='prontuario',
            options={'verbose_name_plural': 'Prontuarios'},
        ),
        migrations.AlterModelOptions(
            name='psr',
            options={'verbose_name_plural': "PSR's"},
        ),
        migrations.AlterModelOptions(
            name='resultadoexamescomplementares',
            options={'verbose_name_plural': 'Resultados de Exames Complementares'},
        ),
        migrations.AlterModelOptions(
            name='sinaisvitaisclinicos',
            options={'verbose_name_plural': 'Sinais Vitais Clinicos'},
        ),
        migrations.AlterModelOptions(
            name='solicitacaoexamescomplementares',
            options={'verbose_name_plural': 'Solicitações Exames Complementares'},
        ),
        migrations.RemoveField(
            model_name='odontogramainicial',
            name='d11',
        ),
        migrations.RemoveField(
            model_name='odontogramainicial',
            name='d12',
        ),
        migrations.RemoveField(
            model_name='odontogramainicial',
            name='d13',
        ),
        migrations.RemoveField(
            model_name='odontogramainicial',
            name='d14',
        ),
        migrations.RemoveField(
            model_name='odontogramainicial',
            name='d15',
        ),
        migrations.RemoveField(
            model_name='odontogramainicial',
            name='d16',
        ),
        migrations.RemoveField(
            model_name='odontogramainicial',
            name='d17',
        ),
        migrations.RemoveField(
            model_name='odontogramainicial',
            name='d18',
        ),
        migrations.RemoveField(
            model_name='odontogramainicial',
            name='d21',
        ),
        migrations.RemoveField(
            model_name='odontogramainicial',
            name='d22',
        ),
        migrations.RemoveField(
            model_name='odontogramainicial',
            name='d23',
        ),
        migrations.RemoveField(
            model_name='odontogramainicial',
            name='d24',
        ),
        migrations.RemoveField(
            model_name='odontogramainicial',
            name='d25',
        ),
        migrations.RemoveField(
            model_name='odontogramainicial',
            name='d26',
        ),
        migrations.RemoveField(
            model_name='odontogramainicial',
            name='d27',
        ),
        migrations.RemoveField(
            model_name='odontogramainicial',
            name='d28',
        ),
        migrations.RemoveField(
            model_name='odontogramainicial',
            name='d31',
        ),
        migrations.RemoveField(
            model_name='odontogramainicial',
            name='d32',
        ),
        migrations.RemoveField(
            model_name='odontogramainicial',
            name='d33',
        ),
        migrations.RemoveField(
            model_name='odontogramainicial',
            name='d34',
        ),
        migrations.RemoveField(
            model_name='odontogramainicial',
            name='d35',
        ),
        migrations.RemoveField(
            model_name='odontogramainicial',
            name='d36',
        ),
        migrations.RemoveField(
            model_name='odontogramainicial',
            name='d37',
        ),
        migrations.RemoveField(
            model_name='odontogramainicial',
            name='d38',
        ),
        migrations.RemoveField(
            model_name='odontogramainicial',
            name='d41',
        ),
        migrations.RemoveField(
            model_name='odontogramainicial',
            name='d42',
        ),
        migrations.RemoveField(
            model_name='odontogramainicial',
            name='d43',
        ),
        migrations.RemoveField(
            model_name='odontogramainicial',
            name='d44',
        ),
        migrations.RemoveField(
            model_name='odontogramainicial',
            name='d45',
        ),
        migrations.RemoveField(
            model_name='odontogramainicial',
            name='d46',
        ),
        migrations.RemoveField(
            model_name='odontogramainicial',
            name='d47',
        ),
        migrations.RemoveField(
            model_name='odontogramainicial',
            name='d48',
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='examefisico',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='infsaudesistemica',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='odontogramainicial',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='prontuario',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='psr',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='resultadoexamescomplementares',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='resultadoexamescomplementares',
            name='res_exa_com',
            field=models.TextField(verbose_name='Resultado Exames Complementares'),
        ),
        migrations.AlterField(
            model_name='sinaisvitaisclinicos',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sinaisvitaisclinicos',
            name='indice',
            field=models.CharField(blank=True, max_length=5, verbose_name='Indíce'),
        ),
        migrations.AlterField(
            model_name='sinaisvitaisclinicos',
            name='pressao_arterial',
            field=models.TextField(blank=True, verbose_name='Pressão Arterial'),
        ),
        migrations.AlterField(
            model_name='sinaisvitaisclinicos',
            name='pulso',
            field=models.TextField(blank=True, verbose_name='Pulso'),
        ),
        migrations.AlterField(
            model_name='sinaisvitaisclinicos',
            name='respiracao',
            field=models.TextField(blank=True, verbose_name='Respiração'),
        ),
        migrations.AlterField(
            model_name='sinaisvitaisclinicos',
            name='resultado',
            field=models.CharField(blank=True, choices=[('Higiene Boa', 'Higiene Boa'), ('Higiene Regular', 'Higiene regular'), ('Higiene Ruim', 'Higiene Ruim')], max_length=15, verbose_name='Resultado'),
        ),
        migrations.AlterField(
            model_name='sinaisvitaisclinicos',
            name='temperatura',
            field=models.TextField(blank=True, verbose_name='Temperatura'),
        ),
        migrations.AlterField(
            model_name='solicitacaoexamescomplementares',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='solicitacaoexamescomplementares',
            name='sol_exa_com',
            field=models.TextField(blank=True, verbose_name='Solicitação Exames Complementares'),
        ),
        migrations.DeleteModel(
            name='EvolucaoPaciente',
        ),
        migrations.DeleteModel(
            name='PlanoTratamentoI',
        ),
        migrations.DeleteModel(
            name='PlanoTratamentoII',
        ),
        migrations.AddField(
            model_name='odontograma',
            name='odontograma_inicial',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odontograma_inicial', to='prontuario.odontogramainicial'),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='prontuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prontuario', to='prontuario.prontuario'),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='prontuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prontuario.prontuario'),
        ),
        migrations.AddField(
            model_name='dente',
            name='doenca',
            field=models.ManyToManyField(blank=True, related_name='dente', to='prontuario.doenca'),
        ),
        migrations.AddField(
            model_name='dente',
            name='procedimento',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='dente', to='prontuario.procedimento'),
        ),
        migrations.AddField(
            model_name='dente',
            name='prontuario',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='dente', to='prontuario.prontuario'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='dente',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='atendimento', to='prontuario.dente'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='prontuario',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='atendimento', to='prontuario.prontuario'),
        ),
        migrations.AddField(
            model_name='odontogramainicial',
            name='diagnostico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odontograma_inicial', to='prontuario.diagnostico'),
        ),
    ]
