# Generated by Django 4.0.3 on 2022-09-09 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinaisvitaisclinicos',
            name='pressao_arterial',
            field=models.TextField(blank=True, verbose_name='Pressão Arterial'),
        ),
        migrations.AlterField(
            model_name='sinaisvitaisclinicos',
            name='pulso',
            field=models.TextField(blank=True, verbose_name='Pulso'),
        ),
        migrations.AlterField(
            model_name='sinaisvitaisclinicos',
            name='respiracao',
            field=models.TextField(blank=True, verbose_name='Respiração'),
        ),
        migrations.AlterField(
            model_name='sinaisvitaisclinicos',
            name='temperatura',
            field=models.TextField(blank=True, verbose_name='Temperatura'),
        ),
    ]
