# Generated by Django 4.0.3 on 2022-09-09 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0002_alter_sinaisvitaisclinicos_pressao_arterial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinaisvitaisclinicos',
            name='indice',
            field=models.IntegerField(verbose_name='Indíce'),
        ),
        migrations.AlterField(
            model_name='sinaisvitaisclinicos',
            name='placa_visivel_11v',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], verbose_name='16V'),
        ),
        migrations.AlterField(
            model_name='sinaisvitaisclinicos',
            name='placa_visivel_16v',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], verbose_name='16V'),
        ),
        migrations.AlterField(
            model_name='sinaisvitaisclinicos',
            name='placa_visivel_26v',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], verbose_name='16V'),
        ),
        migrations.AlterField(
            model_name='sinaisvitaisclinicos',
            name='placa_visivel_31v',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], verbose_name='16V'),
        ),
        migrations.AlterField(
            model_name='sinaisvitaisclinicos',
            name='placa_visivel_36v',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], verbose_name='16V'),
        ),
        migrations.AlterField(
            model_name='sinaisvitaisclinicos',
            name='placa_visivel_46v',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], verbose_name='16V'),
        ),
    ]
