# Generated by Django 4.0.3 on 2022-11-20 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0002_atendimento_dente_diagnostico_doenca_odontograma_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atendimento',
            name='procedimento',
        ),
    ]
