# Generated by Django 4.0.3 on 2022-09-09 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0003_alter_sinaisvitaisclinicos_indice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sinaisvitaisclinicos',
            name='resultado',
        ),
    ]
