# Generated by Django 4.0.3 on 2022-11-21 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0003_remove_dente_procedimento_dente_procedimento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procedimento',
            options={'verbose_name_plural': 'Procedimentos'},
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='dente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prontuario.dente'),
        ),
    ]
