# Generated by Django 4.0.3 on 2022-11-23 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0004_alter_procedimento_options_alter_diagnostico_dente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dente',
            name='doenca',
            field=models.ManyToManyField(blank=True, related_name='doenca', to='prontuario.doenca'),
        ),
        migrations.AlterField(
            model_name='dente',
            name='procedimento',
            field=models.ManyToManyField(blank=True, related_name='procedimento', to='prontuario.procedimento'),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='dente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dente', to='prontuario.dente'),
        ),
        migrations.AlterField(
            model_name='odontogramainicial',
            name='diagnostico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnostico', to='prontuario.diagnostico'),
        ),
        migrations.AlterField(
            model_name='odontogramainicial',
            name='prontuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prontuario_odonto', to='prontuario.prontuario'),
        ),
    ]
