# Generated by Django 4.0.3 on 2022-09-09 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0005_remove_sinaisvitaisclinicos_indice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinaisvitaisclinicos',
            name='placa_visivel_16v',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=1, verbose_name='16V'),
        ),
    ]
