# Generated by Django 4.0.3 on 2022-09-09 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0006_alter_sinaisvitaisclinicos_placa_visivel_16v'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinaisvitaisclinicos',
            name='indice',
            field=models.CharField(blank=True, max_length=5, verbose_name='Indíce'),
        ),
        migrations.AddField(
            model_name='sinaisvitaisclinicos',
            name='resultado',
            field=models.CharField(blank=True, choices=[('Higiene Boa', 'Higiene Boa'), ('Higiene Regular', 'Higiene regular'), ('Higiene Ruim', 'Higiene Ruim')], max_length=15, verbose_name='Resultado'),
        ),
    ]
