# Generated by Django 4.0.3 on 2022-10-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0007_sinaisvitaisclinicos_indice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odontogramainicial',
            name='d11',
            field=models.TextField(blank=True, verbose_name='11'),
        ),
        migrations.AlterField(
            model_name='odontogramainicial',
            name='d12',
            field=models.TextField(blank=True, verbose_name='12'),
        ),
        migrations.AlterField(
            model_name='odontogramainicial',
            name='d13',
            field=models.TextField(blank=True, verbose_name='13'),
        ),
        migrations.AlterField(
            model_name='odontogramainicial',
            name='d14',
            field=models.TextField(blank=True, verbose_name='14'),
        ),
        migrations.AlterField(
            model_name='odontogramainicial',
            name='d15',
            field=models.TextField(blank=True, verbose_name='15'),
        ),
        migrations.AlterField(
            model_name='odontogramainicial',
            name='d16',
            field=models.TextField(blank=True, verbose_name='16'),
        ),
        migrations.AlterField(
            model_name='odontogramainicial',
            name='d17',
            field=models.TextField(blank=True, verbose_name='17'),
        ),
        migrations.AlterField(
            model_name='odontogramainicial',
            name='d18',
            field=models.TextField(blank=True, verbose_name='18'),
        ),
        migrations.AlterField(
            model_name='odontogramainicial',
            name='d21',
            field=models.TextField(blank=True, verbose_name='21'),
        ),
        migrations.AlterField(
            model_name='odontogramainicial',
            name='d22',
            field=models.TextField(blank=True, verbose_name='22'),
        ),
        migrations.AlterField(
            model_name='odontogramainicial',
            name='d23',
            field=models.TextField(blank=True, verbose_name='23'),
        ),
        migrations.AlterField(
            model_name='odontogramainicial',
            name='d24',
            field=models.TextField(blank=True, verbose_name='24'),
        ),
        migrations.AlterField(
            model_name='odontogramainicial',
            name='d25',
            field=models.TextField(blank=True, verbose_name='25'),
        ),
        migrations.AlterField(
            model_name='odontogramainicial',
            name='d26',
            field=models.TextField(blank=True, verbose_name='26'),
        ),
        migrations.AlterField(
            model_name='odontogramainicial',
            name='d27',
            field=models.TextField(blank=True, verbose_name='27'),
        ),
        migrations.AlterField(
            model_name='odontogramainicial',
            name='d28',
            field=models.TextField(blank=True, verbose_name='28'),
        ),
        migrations.AlterField(
            model_name='odontogramainicial',
            name='d31',
            field=models.TextField(blank=True, verbose_name='31'),
        ),
        migrations.AlterField(
            model_name='odontogramainicial',
            name='d32',
            field=models.TextField(blank=True, verbose_name='32'),
        ),
        migrations.AlterField(
            model_name='odontogramainicial',
            name='d33',
            field=models.TextField(blank=True, verbose_name='33'),
        ),
        migrations.AlterField(
            model_name='odontogramainicial',
            name='d34',
            field=models.TextField(blank=True, verbose_name='34'),
        ),
        migrations.AlterField(
            model_name='odontogramainicial',
            name='d35',
            field=models.TextField(blank=True, verbose_name='35'),
        ),
        migrations.AlterField(
            model_name='odontogramainicial',
            name='d36',
            field=models.TextField(blank=True, verbose_name='36'),
        ),
        migrations.AlterField(
            model_name='odontogramainicial',
            name='d37',
            field=models.TextField(blank=True, verbose_name='37'),
        ),
        migrations.AlterField(
            model_name='odontogramainicial',
            name='d38',
            field=models.TextField(blank=True, verbose_name='38'),
        ),
        migrations.AlterField(
            model_name='odontogramainicial',
            name='d41',
            field=models.TextField(blank=True, verbose_name='41'),
        ),
        migrations.AlterField(
            model_name='odontogramainicial',
            name='d42',
            field=models.TextField(blank=True, verbose_name='42'),
        ),
        migrations.AlterField(
            model_name='odontogramainicial',
            name='d43',
            field=models.TextField(blank=True, verbose_name='43'),
        ),
        migrations.AlterField(
            model_name='odontogramainicial',
            name='d44',
            field=models.TextField(blank=True, verbose_name='44'),
        ),
        migrations.AlterField(
            model_name='odontogramainicial',
            name='d45',
            field=models.TextField(blank=True, verbose_name='45'),
        ),
        migrations.AlterField(
            model_name='odontogramainicial',
            name='d46',
            field=models.TextField(blank=True, verbose_name='46'),
        ),
        migrations.AlterField(
            model_name='odontogramainicial',
            name='d47',
            field=models.TextField(blank=True, verbose_name='47'),
        ),
        migrations.AlterField(
            model_name='odontogramainicial',
            name='d48',
            field=models.TextField(blank=True, verbose_name='48'),
        ),
        migrations.AlterField(
            model_name='solicitacaoexamescomplementares',
            name='sol_exa_com',
            field=models.TextField(blank=True, verbose_name='Solicitação exames Complementares'),
        ),
    ]
