# Generated by Django 4.0.3 on 2023-04-11 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0007_estenografia_remove_dente_doenca_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estenografia',
            options={'verbose_name_plural': 'Estenografia'},
        ),
    ]
