# Generated by Django 4.0.3 on 2023-04-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0008_alter_estenografia_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dente',
            name='nome',
            field=models.CharField(blank=True, max_length=3, verbose_name='Dente'),
        ),
    ]
