# Generated by Django 4.0.3 on 2023-04-15 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0009_alter_dente_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='odontograma',
            name='dente',
        ),
        migrations.AddField(
            model_name='odontograma',
            name='dente_11',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odontograma_dente_11', to='prontuario.dente'),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='dente_12',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odontograma_dente_12', to='prontuario.dente'),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='dente_13',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odontograma_dente_13', to='prontuario.dente'),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='dente_14',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odontograma_dente_14', to='prontuario.dente'),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='dente_15',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odontograma_dente_15', to='prontuario.dente'),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='dente_16',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odontograma_dente_16', to='prontuario.dente'),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='dente_17',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odontograma_dente_17', to='prontuario.dente'),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='dente_18',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odontograma_dente_18', to='prontuario.dente'),
        ),
    ]
