# Generated by Django 4.0.3 on 2023-04-15 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0010_remove_odontograma_dente_odontograma_dente_11_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='odontograma',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='odontograma',
            name='updated_at',
        ),
    ]
