# Generated by Django 4.0.3 on 2023-04-15 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0011_remove_odontograma_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='odontograma',
            name='dente_21',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odontograma_dente_21', to='prontuario.dente'),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='dente_22',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odontograma_dente_22', to='prontuario.dente'),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='dente_23',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odontograma_dente_23', to='prontuario.dente'),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='dente_24',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odontograma_dente_24', to='prontuario.dente'),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='dente_25',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odontograma_dente_25', to='prontuario.dente'),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='dente_26',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odontograma_dente_26', to='prontuario.dente'),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='dente_27',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odontograma_dente_27', to='prontuario.dente'),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='dente_28',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odontograma_dente_28', to='prontuario.dente'),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='dente_31',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odontograma_dente_31', to='prontuario.dente'),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='dente_32',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odontograma_dente_32', to='prontuario.dente'),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='dente_33',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odontograma_dente_33', to='prontuario.dente'),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='dente_34',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odontograma_dente_34', to='prontuario.dente'),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='dente_35',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odontograma_dente_35', to='prontuario.dente'),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='dente_36',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odontograma_dente_36', to='prontuario.dente'),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='dente_37',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odontograma_dente_37', to='prontuario.dente'),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='dente_38',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odontograma_dente_38', to='prontuario.dente'),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='dente_41',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odontograma_dente_41', to='prontuario.dente'),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='dente_42',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odontograma_dente_42', to='prontuario.dente'),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='dente_43',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odontograma_dente_43', to='prontuario.dente'),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='dente_44',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odontograma_dente_44', to='prontuario.dente'),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='dente_45',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odontograma_dente_45', to='prontuario.dente'),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='dente_46',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odontograma_dente_46', to='prontuario.dente'),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='dente_47',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odontograma_dente_47', to='prontuario.dente'),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='dente_48',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odontograma_dente_48', to='prontuario.dente'),
        ),
    ]
