# Generated by Django 4.0.3 on 2022-08-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('nome_social', models.CharField(blank=True, max_length=200, verbose_name='Nome Social')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('sexo_biologico', models.CharField(blank=True, max_length=200, verbose_name='Sexo Biologico')),
                ('rg', models.CharField(blank=True, max_length=200, verbose_name='RG')),
                ('cpf', models.CharField(max_length=200, verbose_name='CPF')),
                ('raca', models.CharField(max_length=200, verbose_name='Raça')),
                ('estado_civil', models.CharField(max_length=200, verbose_name='Estado Civil')),
                ('grau_instrucao', models.CharField(max_length=200, verbose_name='Grau de Instrução')),
                ('endereco', models.CharField(max_length=200, verbose_name='Endereço')),
                ('cep', models.CharField(max_length=200, verbose_name='CEP')),
                ('bairro', models.CharField(max_length=200, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=200, verbose_name='Cidade')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('telefone_celular', models.CharField(max_length=200, verbose_name='Telefone Celular')),
                ('informacoes_complementares', models.TextField(verbose_name='Informações Complementares')),
            ],
        ),
        migrations.CreateModel(
            name='PacienteInfantil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsavel', models.CharField(max_length=200, verbose_name='Reponsavel')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('nome_social', models.CharField(blank=True, max_length=200, verbose_name='Nome Social')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('sexo_biologico', models.CharField(max_length=200, verbose_name='Sexo Biologico')),
                ('rg', models.CharField(blank=True, max_length=200, verbose_name='RG')),
                ('cpf', models.CharField(max_length=200, verbose_name='CPF')),
                ('raca', models.CharField(max_length=200, verbose_name='Raça')),
                ('estado_civil', models.CharField(max_length=200, verbose_name='Estado Civil')),
                ('grau_instrucao', models.CharField(max_length=200, verbose_name='Grau de Instrução')),
                ('endereco', models.CharField(max_length=200, verbose_name='Endereço')),
                ('cep', models.CharField(max_length=200, verbose_name='CEP')),
                ('bairro', models.CharField(max_length=200, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=200, verbose_name='Cidade')),
                ('uf', models.CharField(max_length=200, verbose_name='UF')),
                ('telefone_celular', models.CharField(max_length=200, verbose_name='Telefone Celular')),
                ('informacoes_complementares', models.TextField(verbose_name='Informações Complementares')),
            ],
            options={
                'verbose_name': 'Paciente Infantil',
                'verbose_name_plural': 'Pacientes Infantis',
            },
        ),
    ]
