# Generated by Django 4.0.3 on 2023-04-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testando', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Testes',
            },
        ),
        migrations.CreateModel(
            name='Teste2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testando', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Teste2s',
            },
        ),
        migrations.AddField(
            model_name='paciente',
            name='prontuario',
            field=models.CharField(blank=True, max_length=200, verbose_name='prontuario'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='bairro',
            field=models.CharField(blank=True, max_length=200, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cep',
            field=models.CharField(blank=True, max_length=200, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cidade',
            field=models.CharField(blank=True, max_length=200, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(blank=True, max_length=200, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='data_nascimento',
            field=models.DateField(blank=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='estado_civil',
            field=models.CharField(blank=True, max_length=200, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='grau_instrucao',
            field=models.CharField(blank=True, max_length=200, verbose_name='Grau de Instrução'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='informacoes_complementares',
            field=models.TextField(blank=True, verbose_name='Informações Complementares'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='raca',
            field=models.CharField(blank=True, max_length=200, verbose_name='Raça'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefone_celular',
            field=models.CharField(blank=True, max_length=200, verbose_name='Telefone Celular'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='uf',
            field=models.CharField(blank=True, max_length=2, verbose_name='UF'),
        ),
    ]
