# Generated by Django 4.0.3 on 2023-05-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_teste_teste2_paciente_prontuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
