# Generated by Django 4.0.3 on 2023-04-20 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distribuicao', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Disciplina',
        ),
    ]
