# Generated by Django 4.0.3 on 2022-11-20 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0002_atendimento_dente_diagnostico_doenca_odontograma_and_more'),
        ('usuarios', '0002_discente_imagem_docente_imagem_funcionario_imagem_and_more'),
        ('distribuicao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_hora', models.DateTimeField(auto_now=True, verbose_name='Data')),
                ('done', models.BooleanField(default=False)),
                ('atendimento', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='agendamento', to='prontuario.atendimento')),
                ('discente', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='agendamento', to='usuarios.discente')),
                ('disciplina', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='agendamento', to='distribuicao.disciplina')),
                ('docente', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='agendamento', to='usuarios.docente')),
                ('prontuario', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='agendamento', to='prontuario.prontuario')),
            ],
        ),
    ]
