# Generated by Django 4.0.3 on 2022-11-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribuicao', '0002_agendamento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamento',
            options={'verbose_name_plural': 'Agendamentos'},
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='data_hora',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data'),
        ),
    ]
