# Generated by Django 4.0.3 on 2022-11-20 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distribuicao', '0003_alter_agendamento_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='updated_at',
        ),
    ]
