# Generated by Django 4.0.3 on 2022-11-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribuicao', '0004_remove_agendamento_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='data_hora',
            field=models.DateTimeField(blank=True, verbose_name='Data'),
        ),
    ]
