# Generated by Django 4.0.3 on 2022-11-20 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0002_atendimento_dente_diagnostico_doenca_odontograma_and_more'),
        ('distribuicao', '0005_alter_agendamento_data_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='atendimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agendamento', to='prontuario.atendimento'),
        ),
    ]
