# Generated by Django 4.0.3 on 2022-11-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_funcionario_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='imagem',
            field=models.ImageField(blank=True, default='media/padrao.png', null=True, upload_to=''),
        ),
    ]
