# Generated by Django 4.0.3 on 2022-11-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_funcionario_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discente',
            name='imagem',
            field=models.ImageField(blank=True, default='media/padrao.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='docente',
            name='imagem',
            field=models.ImageField(blank=True, default='media/padrao.png', null=True, upload_to=''),
        ),
    ]
